# -*- coding: utf-8 -*-
"""Malnurtition_refresh_sql.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17bPsiIdbazgM-3JWrlHpjiN0_J3kLmX0
"""

import os
import openpyxl
import glob
# Get the path of the active workbook
filepath = os.path.abspath(os.getcwd())

filename_list = glob.glob('Raw/JME_Country_Estimates*.xlsx')

# Load the first file in the list (assuming there is at least one file)
wb = openpyxl.load_workbook(filename=filename_list[0])
wb.min_row = 1
wb.min_column = 1

# Loop through each worksheet in the current workbook
for ws in wb.worksheets:
    # Create a new workbook with the same name as the worksheet
    new_wb = openpyxl.Workbook()
    new_ws = new_wb.active
    new_ws.title = ws.title
    
    # Copy the values and formatting from the original worksheet to the new worksheet
    for row in ws.rows:
        for cell in row:
            new_ws[cell.coordinate].value = cell.value
    # Save the new worksheet as a separate file with the same name as the worksheet
    new_wb.save(filepath + '/Temp/' + ws.title + '.xlsx')
    
# Close the original workbook
wb.close()

import pandas as pd
stuntprop= pd.read_excel("Temp/Stunting Proportion (Model).xlsx")

#Get stunt propoption data for updated year
load_year=stuntprop.columns[-1]
stuntprop = stuntprop[[ 'ISO code','Country and areas','Estimate',load_year]]
stuntprop['Year']=load_year[:4]
stuntprop.rename(columns={"Country and areas": "Country", "ISO code": "ISO_code",load_year:"stunting_proportion"}, inplace=True)
stuntprop= stuntprop.loc[ stuntprop['Estimate'] == 'Point Estimate'].reset_index().drop(["Estimate","index"], axis = 1)
stuntprop.head()

stuntaffected= pd.read_excel("Temp/Stunting Numb Affected(Model).xlsx")

#Get stunt affected data for updated year
load_year=stuntaffected.columns[-1]
stuntaffected = stuntaffected[[ 'ISO code','Country and areas','Estimate',load_year]]
stuntaffected['Year']=load_year[:4]
stuntaffected.rename(columns={"Country and areas": "Country", "ISO code": "ISO_code",load_year:"stunting_affected"}, inplace=True)
stuntaffected= stuntaffected.loc[ stuntaffected['Estimate'] == 'Point Estimate'].reset_index().drop(["Estimate","index"], axis = 1)
stuntaffected.head()

overwgtaffected= pd.read_excel("Temp/Overweight Numb Affected(Model).xlsx")

#Get overweight affected data for updated year
load_year=overwgtaffected.columns[-1]
overwgtaffected = overwgtaffected[[ 'ISO code','Country and areas','Estimate',load_year]]
overwgtaffected['Year']=load_year[:4]
overwgtaffected.rename(columns={"Country and areas": "Country", "ISO code": "ISO_code",load_year:"overweight_affected"}, inplace=True)
overwgtaffected= overwgtaffected.loc[ overwgtaffected['Estimate'] == 'Point Estimate'].reset_index().drop(["Estimate","index"], axis = 1)
overwgtaffected.head()

import pandas as pd
overweightprop= pd.read_excel("Temp/Overweight Proportion (Model).xlsx")

#Get overweight propoption data for updated year
load_year=overweightprop.columns[-1]
overweightprop = overweightprop[[ 'ISO code','Country and areas','Estimate',load_year]]
overweightprop['Year']=load_year[:4]
overweightprop.rename(columns={"Country and areas": "Country", "ISO code": "ISO_code",load_year:"overweight_proportion"}, inplace=True)
overweightprop= overweightprop.loc[ overweightprop['Estimate'] == 'Point Estimate'].reset_index().drop(["Estimate","index"], axis = 1)
overweightprop.head()

print(overweightprop.shape)
print(overwgtaffected.shape)
print(stuntprop.shape)
print(stuntaffected.shape)

Final_Summary =overweightprop.merge(overwgtaffected).merge(stuntprop).merge(stuntaffected)
Final_Summary=Final_Summary[['ISO_code','Country','Year','overweight_proportion','overweight_affected','stunting_proportion','stunting_affected']]
Final_Summary.head()
source="Source"+load_year[:4]
os.mkdir(source)
Final_Summary.to_excel(source+"/Malnutrition_impact_hist.xlsx", index=False)
survey= pd.read_excel("Temp/Survey Estimates.xlsx")

survey.head()


#Get country_details data
country_details= survey[['ISO code','Country and areas','United Nations Region','WHO Region','UNICEF Region']].copy()

country_details.rename(columns={"ISO code":"ISO_code","Country and areas": "Country", "United Nations Region": "UN_region","WHO Region":"WHO_region","UNICEF Region":"UNICEF_region"}, inplace=True)

country_details=country_details.drop_duplicates().reset_index().drop(["index"], axis = 1)

country_details.to_excel(source+"/country_details.xlsx", index=False)

#Get income_classification data
income_classification= survey[['ISO code','World Bank Income Classification','LDC','LIFD','LLDC or SIDS']].copy()
	

income_classification.rename(columns={"ISO code":"ISO_code","World Bank Income Classification": "wb_income_class", "LLDC or SIDS":"LLDC_SIDS"}, inplace=True)

income_classification=income_classification.drop_duplicates().reset_index().drop(["index"], axis = 1)

income_classification.to_excel(source+"/income_classification.xlsx", index=False)

#Delete All temporary Files
dir = 'Temp/'
for f in os.listdir(dir):
    os.remove(os.path.join(dir, f))

